### ISSUE TITLE
Initial admin

### ISSUE THREAD

**Issue by cipp-svbgroup** [CyberCX-STA/PurpleOps#8]
Hi

Just wanting to test this out and I think I'm missing something. I've looked at the docs and cannot find anywhere that details where the initial admin username and password is generated/stored so can't login. Can someone shed some light on this please?

Many thanks in advance.

**Comment by cipp-svbgroup** [comment]
As an update to above, this is using the docker version. I have reviewed all the logs and cannot find anything that shows a generated user admin account and password during the initial compose.

**Comment by wsummerhill** [comment]
I actually just had this same issue while spinning up the server with docker compose. I tried these steps and fixed it:

1. Stop the docker container
2. Remove all containers
    - `docker rm -f $(docker ps -a -q)`
    - `docker volume rm $(docker volume ls -q)`
4. Remove the whole PurpleOps directory
5. Git clone the PurpleOps directory again
6. Try re-installing with docker compose - This time I got the admin username/password from the output line `Created initial admin:...`

**Comment by Harrison-Mitchell** [comment]
@cipp-svbgroup Any luck in the end? I plan on closing the ticket should there be no further updates

**Comment by cipp-svbgroup** [comment]
No joy sadly. docker rm or docker volume rm commands above give me a permission denied error, even when run using sudo. Investigating further.

**Comment by cipp-svbgroup** [comment]
Followed instructions above. Now when I try and start docker image I get the following error:

Pulling MITRE Tactics
Traceback (most recent call last):
  File "/usr/src/app/seeder.py", line 219 in <module>
    parseMitreTactics()
  File "/usr/src/app/seeder.py?, line 46, in parseMitreTactics
    rows, headers = pullMitreAttack("tactics")
  File "/usr/src/app/seeder", line 33, in pullMitreAttack
    url = [x for x in req if "xlsx" in x and "enterprise" in x and "docs" in x and component in x] [0]

IndexError: list index out of range

There's a whole bunch of other errors and then TypeError: 'NoneType' object is not iterable

Master shutdown, and reason Worker failed to boot.

**Comment by cipp-svbgroup** [comment]
Yes, this is now resolved. Apologies for the delay in responding. Cheers

**Comment by Sebull-git** [comment]
Hi, 
still having issues with the initial admin. 
Error message is invalid email: Install Log shows me admin@purpleops.com I've checked multiple times
Thanks in advance if anyone can help me
